package:
  name: statistical_mechanics_teaching
  version: 0.9.0

source:
  git_url: https://github.com/mabau/statistical_mechanics_teaching.git
  git_rev: master


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - lammps

extra:
    maintainers:
       - Martin Bauer
